### ISSUE TITLE
keystorepassword nicht gefunden

### ISSUE THREAD

**Issue by stillchris01** [randombyte-developer/SGLVertretungsplan#53]
Beim versuch, das Projekt zu öffnen, kam folgender Fehler: 

_ERROR: C:\Users\sven3\Entwicklung\Android\keystorepassword (Das System kann den angegebenen Pfad nicht finden)_

Da ich mir das Projekt ein wenig genauer ansehen will, bräuchte ich diese Datei. 
Danke im voraus!

**Comment by randombyte-developer** [comment]
Moin!

Ich hab gesehen, dass du grad dabei bist dich selbst an einer Vertretungsplan-App zu versuchen.

Das Signing ist eigentlich nur für den Release-Build relevant, der im PlayStore veröffentlicht ist. Zum Testen der App über ADB wird sowieso ein Debug-Build verwendet, der kein Signing braucht. Die `.jks` Datei und die dazugehörigen Daten werden zum Signieren gebraucht. Das willst du aber eigentlich nicht machen.
Es sollte ausreichen diesen Zeilen auzukommentieren: https://github.com/randombyte-developer/SGLVertretungsplan/blob/master/app/build.gradle#L15-L22

Btw, weitere Dinge können wir auf Discord besprechen. Meine Email ist `apps.randombyte@gmail.com`. Die Email fliegt sowieso schon im Internet rum, mein Discord-Account aber noch nicht :) Also wenn du Bock hast kann ich dir noch weitere Tipps geben bei deiner App. Einfach deinen Discord Namen an die Email schicken.

Sven

**Comment by stillchris01** [comment]
Danke erstmal für die Antwort, hätte nicht gerechnet das du zurückschreibst ^^

Ich bin schon dabei die App komplett neu zu machen. Habe auch schon ein gutes Grundgerüst aufgebaut, was fehlt ist halt noch die Adresse um die Vertretungsstunden zu beziehen und viele kleinigkeiten wie ein Darkmode und ein guter Loginscreen. Bei einigen Sachen könntest du mir wirklich echt helfen...

Und wegen dem Key:
Android Studio streikt, der will ohne das kaum Dateien öffnen, geschweige denn irgendein build machen. Der stoppt ja schon bei der Initialisierung.

**Comment by stillchris01** [comment]
(Ja ich war so blöde das ich gedacht hätte du hast mir eine Email geschrieben :o)

**Comment by randombyte-developer** [comment]
Hab dich auf Discord angeschrieben. (Musst mich wohl als Freund hinzufügen, damit ich dir was schreiben kann)
